#!/usr/bin/bash

##wget --user-agent=Mozilla/5.0 "https://query1.finance.yahoo.com/v7/finance/download/$1?period1=1670533578&period2=1702069578&interval=1d&events=history&includeAdjustedClose=true" -O /home/tolga.ozaltin/pypy/scripts/r
##wget --user-agent=Mozilla/5.0 "https://query1.finance.yahoo.com/v7/finance/download/$1?period1=1670782902&period2=1702318902&interval=1d&events=history&includeAdjustedClose=true" -O /home/tolga.ozaltin/pypy/scripts/r
wget --user-agent=Mozilla/5.0 "https://query1.finance.yahoo.com/v7/finance/download/$1?period1=0&period2=3902935074&interval=1d&events=history&includeAdjustedClose=true" -O /home/tolga.ozaltin/pypy/scripts/r

### https://query1.finance.yahoo.com/v7/finance/download/NVDA?period1=1671399074&period2=1702935074&interval=1d&events=history&includeAdjustedClose=true
#wget --user-agent=Mozilla/5.0 "https://query1.finance.yahoo.com/v7/finance/download/$1?period1=1671399074&period2=1702935074&interval=1d&events=history&includeAdjustedClose=true" -O /home/tolga.ozaltin/pypy/scripts/r
./p4
